version: "3.8"



services:
  db:
    image: postgres:14.10
    container_name: db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  fastapi_backend:
    depends_on:
      - db
    container_name: fastapi_backend
    build:
        context: ./backend
        dockerfile: Dockerfile
    env_file: 
      - ./.env