version: '3.3'

volumes:
  pg_data:

services:
  db:
    container_name: db
    image: postgres:13.3
    env_file: 
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data