version: "3.8"

volumes:
  pg_data:

services:
  db:
    image: postgres:14.10
    container_name: db
    restart: always
    env_file:
      - ../backend/.env
    volumes:
        - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
        - pg_data:/var/lib/postgresql/data
  fastapi_backend:
    depends_on:
      - db
    container_name: fastapi_backend
    build:
        context: ../backend
        dockerfile: Dockerfile
    env_file: 
      - ../backend/.env
    ports:
      - 8000:8000