"""add setnull delete

Revision ID: 775ab7e7c282
Revises: 1f5131723912
Create Date: 2023-12-31 00:49:43.801912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "775ab7e7c282"
down_revision: Union[str, None] = "1f5131723912"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "services",
        "specialization_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.drop_constraint(
        "services_specialization_id_fkey", "services", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "services",
        "specializations",
        ["specialization_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "services", type_="foreignkey")
    op.create_foreign_key(
        "services_specialization_id_fkey",
        "services",
        "specializations",
        ["specialization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "services",
        "specialization_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
