"""add model service

Revision ID: 2aa867b692a1
Revises: 15e586f25e26
Create Date: 2023-12-22 10:24:42.503133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2aa867b692a1"
down_revision: Union[str, None] = "15e586f25e26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "services",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("specialist_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["specialist_id"],
            ["specialists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "specialists", sa.Column("service_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None, "specialists", "services", ["service_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "specialists", type_="foreignkey")
    op.drop_column("specialists", "service_id")
    op.drop_table("services")
    # ### end Alembic commands ###
