"""add cascade delete

Revision ID: 1f5131723912
Revises: 0b110f6c7a0f
Create Date: 2023-12-31 00:18:44.637416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f5131723912"
down_revision: Union[str, None] = "0b110f6c7a0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "services",
        "specialization_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_constraint(
        "services_specialization_id_fkey", "services", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "services",
        "specializations",
        ["specialization_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "services", type_="foreignkey")
    op.create_foreign_key(
        "services_specialization_id_fkey",
        "services",
        "specializations",
        ["specialization_id"],
        ["id"],
    )
    op.alter_column(
        "services",
        "specialization_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###
