"""empty message

Revision ID: dedd9fa9fd6a
Revises: 775ab7e7c282
Create Date: 2023-12-31 17:28:58.503092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dedd9fa9fd6a"
down_revision: Union[str, None] = "775ab7e7c282"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("services", "price")
    op.add_column(
        "specialist_service_association",
        sa.Column("price", sa.Integer(), nullable=True),
    )
    op.add_column(
        "specialist_service_association",
        sa.Column("description", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("specialist_service_association", "description")
    op.drop_column("specialist_service_association", "price")
    op.add_column(
        "services",
        sa.Column("price", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
