"""add m2m service_specialist

Revision ID: 84ce847b6c16
Revises: e2bc341affe2
Create Date: 2023-12-27 16:18:52.244599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "84ce847b6c16"
down_revision: Union[str, None] = "e2bc341affe2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "specialist_service_association",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Integer(), nullable=False),
        sa.Column("specialist_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
        ),
        sa.ForeignKeyConstraint(
            ["specialist_id"],
            ["specialists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "service_id", "specialist_id", name="idx_unique_service_specialist"
        ),
    )
    op.add_column("services", sa.Column("duration", sa.Integer(), nullable=False))
    op.drop_constraint("services_specialist_id_fkey", "services", type_="foreignkey")
    op.drop_column("services", "specialist_id")
    op.drop_constraint("specialists_service_id_fkey", "specialists", type_="foreignkey")
    op.drop_column("specialists", "service_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "specialists",
        sa.Column("service_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "specialists_service_id_fkey", "specialists", "services", ["service_id"], ["id"]
    )
    op.add_column(
        "services",
        sa.Column("specialist_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "services_specialist_id_fkey",
        "services",
        "specialists",
        ["specialist_id"],
        ["id"],
    )
    op.drop_column("services", "duration")
    op.drop_table("specialist_service_association")
    # ### end Alembic commands ###
