"""add m2m specialist_specialization

Revision ID: a8f2f5f74699
Revises: c6742c7efd4f
Create Date: 2023-12-28 10:01:18.043482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a8f2f5f74699"
down_revision: Union[str, None] = "c6742c7efd4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "specialist_specialization_association",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("specialist_id", sa.Integer(), nullable=False),
        sa.Column("specialization_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["specialist_id"],
            ["specialists.id"],
        ),
        sa.ForeignKeyConstraint(
            ["specialization_id"],
            ["specializations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "specialist_id",
            "specialization_id",
            name="idx_unique_specialist_specialist",
        ),
    )
    op.alter_column(
        "specialists",
        "telegram_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.drop_constraint(
        "specialists_specialization_id_fkey", "specialists", type_="foreignkey"
    )
    op.drop_column("specialists", "specialization_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "specialists",
        sa.Column(
            "specialization_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        "specialists_specialization_id_fkey",
        "specialists",
        "specializations",
        ["specialization_id"],
        ["id"],
    )
    op.alter_column(
        "specialists",
        "telegram_id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_table("specialist_specialization_association")
    # ### end Alembic commands ###
