"""drop relation spec-specialization, add relation service-specialization

Revision ID: 20f1624cf4d5
Revises: a8f2f5f74699
Create Date: 2023-12-30 20:46:48.949186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20f1624cf4d5"
down_revision: Union[str, None] = "a8f2f5f74699"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("specialist_specialization_association")
    op.add_column(
        "services",
        sa.Column("specialization_id", sa.Integer(), nullable=False),
    )
    op.create_foreign_key(
        None, "services", "specializations", ["specialization_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "services", type_="foreignkey")
    op.drop_column("services", "specialization_id")
    op.create_table(
        "specialist_specialization_association",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "specialist_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "specialization_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["specialist_id"],
            ["specialists.id"],
            name="specialist_specialization_association_specialist_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["specialization_id"],
            ["specializations.id"],
            name="specialist_specialization_association_specialization_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "id", name="specialist_specialization_association_pkey"
        ),
        sa.UniqueConstraint(
            "specialist_id",
            "specialization_id",
            name="idx_unique_specialist_specialist",
        ),
    )
    # ### end Alembic commands ###
