"""add profile specialist table

Revision ID: 7c76b31ccc48
Revises: b544c4d051a1
Create Date: 2024-01-29 22:24:12.990982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7c76b31ccc48"
down_revision: Union[str, None] = "b544c4d051a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profileinfospecialists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("specialist", sa.Integer(), nullable=False),
        sa.Column("start_work", sa.Time(), nullable=True),
        sa.Column("end_work", sa.Time(), nullable=True),
        sa.Column("busy_time", postgresql.ARRAY(sa.Time()), nullable=True),
        sa.ForeignKeyConstraint(
            ["specialist"],
            ["specialists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("specialist"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profileinfospecialists")
    # ### end Alembic commands ###
