"""empty message

Revision ID: 2f41a0143c50
Revises: dedd9fa9fd6a
Create Date: 2024-01-05 22:05:54.023726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2f41a0143c50"
down_revision: Union[str, None] = "dedd9fa9fd6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("records", sa.Column("note", sa.String(length=256), nullable=False))
    op.add_column("records", sa.Column("service_id", sa.Integer(), nullable=False))
    op.alter_column("records", "is_free", existing_type=sa.BOOLEAN(), nullable=True)
    op.create_foreign_key(None, "records", "services", ["service_id"], ["id"])
    op.drop_column("records", "title")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "records",
        sa.Column("title", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "records", type_="foreignkey")
    op.alter_column("records", "is_free", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_column("records", "service_id")
    op.drop_column("records", "note")
    # ### end Alembic commands ###
